# Generated by Django 5.2.3 on 2025-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miappGraficacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('presion', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
