# Generated by Django 5.2.3 on 2025-06-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miappGraficacion', '0002_medicion_delete_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicion',
            old_name='humedad',
            new_name='sensor1',
        ),
        migrations.RenameField(
            model_name='medicion',
            old_name='peso',
            new_name='sensor2',
        ),
        migrations.RenameField(
            model_name='medicion',
            old_name='presion',
            new_name='sensor3',
        ),
        migrations.RenameField(
            model_name='medicion',
            old_name='temperatura',
            new_name='sensor4',
        ),
        migrations.RenameField(
            model_name='medicion',
            old_name='velocidad',
            new_name='sensor5',
        ),
    ]
