# Generated by Django 5.2.3 on 2025-07-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miappGraficacion', '0003_rename_humedad_medicion_sensor1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicion',
            old_name='nombre',
            new_name='nombre_fecha_hora',
        ),
    ]
